### ISSUE TITLE
No README doc

### ISSUE THREAD

**Issue by NitishDeshpande** [Shasidhar/dynamic-streaming#1]
Can you update the README doc mentioning briefly about the project and steps to run the application and get a hang of it? I came to this project from an answer for a SO question. Link below,
http://stackoverflow.com/questions/41721240/what-is-the-best-way-to-restart-spark-streaming-application

**Comment by Shasidhar** [comment]
Added readme for main branches.

Also you can look quickly into this talk https://www.youtube.com/watch?v=Hocq9nrLrwE where i have discussed about the code in depth.
